version: '3.7'

networks:
  native-spark:

services:
  vega_master:
    image: vega:latest
    ports:
      - "3000"
    tty: true
    networks:
      native-spark:
    volumes:
      - type: "bind"
        source: "../target"
        target: "/home/dev"
    environment:
      VEGA_DEPLOYMENT_MODE: distributed
    depends_on:
      - vega_worker

  vega_worker:
    image: vega:latest
    ports:
      - "10500"
      - "22"
    tty: true
    networks:
      native-spark:
